# Generated by Django 2.2.2 on 2019-07-01 06:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0012_auto_20190701_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 6, 37, 38, 150785)),
        ),
    ]
