# Generated by Django 2.2.2 on 2019-06-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(max_length=3),
        ),
    ]
