# Generated by Django 2.2.2 on 2019-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190625_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
