# Generated by Django 2.2.2 on 2019-06-27 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20190627_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 6, 6, 6, 720833)),
        ),
    ]
