# Generated by Django 2.2.2 on 2019-06-28 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0033_auto_20190627_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 7, 0, 18, 913225)),
        ),
    ]
