# Generated by Django 2.2.2 on 2019-06-28 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_auto_20190628_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 7, 10, 46, 229113)),
        ),
    ]
