# Generated by Django 2.2.2 on 2019-06-28 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0036_auto_20190628_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 7, 18, 28, 736608)),
        ),
    ]
