# Generated by Django 2.2.2 on 2019-07-01 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0037_auto_20190628_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 5, 43, 40, 868172)),
        ),
    ]
