# Generated by Django 2.2.2 on 2019-07-01 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0038_auto_20190701_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 6, 37, 38, 134857)),
        ),
    ]
