# Generated by Django 2.2.2 on 2019-07-01 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0039_auto_20190701_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 9, 22, 54, 762914)),
        ),
    ]
