# Generated by Django 2.2.2 on 2019-06-17 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default=datetime.datetime(2019, 6, 17, 8, 36, 16, 455483, tzinfo=utc))),
                ('duedate', models.DateField(default=datetime.datetime(2019, 6, 17, 8, 36, 16, 455509, tzinfo=utc))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Category')),
            ],
        ),
    ]
