# Generated by Django 2.2.2 on 2019-07-01 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0031_auto_20190628_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 5, 43, 40, 870880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 5, 43, 40, 870905, tzinfo=utc)),
        ),
    ]
