# Generated by Django 2.2.2 on 2019-07-01 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0032_auto_20190701_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 6, 37, 38, 137549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 6, 37, 38, 137575, tzinfo=utc)),
        ),
    ]
