# Generated by Django 2.2.2 on 2019-07-01 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0033_auto_20190701_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 22, 54, 765626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 22, 54, 765651, tzinfo=utc)),
        ),
    ]
